### ISSUE TITLE
Pydantic Default Fields for Nested Models are marked as required

### ISSUE THREAD

**Issue by tungalbert99** [brentyi/tyro#108]
I'm trying to provide defaults of nested pydantic models but the defaults don't show up and are requested as "required". 

Steps for reproduction: 
```
from typing import Literal

import pydantic
import tyro

SourceFlaskSize = Literal[125, 250, 500]


class FlaskConfig(pydantic.BaseModel):
    id: str
    size: SourceFlaskSize
    initial_volume: int
    desired_end_volume: int | None = None


class Config(pydantic.BaseModel):
    source_flasks: list[FlaskConfig] = pydantic.Field(
        [FlaskConfig(id="Flask 1", size=250, initial_volume=50)],
        min_length=1,
        max_length=8,
    )
    
    source_flask: FlaskConfig = pydantic.Field(
        FlaskConfig(id="Flask 1", size=250, initial_volume=50)
    )

    test_list: list[int] = pydantic.Field([5], min_length=1, max_length=8)


if __name__ == "__main__":
    test_item = tyro.cli(Config, prog="hello")

```
It's hard to tell if the min_length/max_length requirements work with tyro but in any case the error is that the default `FlaskConfig` is provided in pydantic but tyro seems to think it's not. 

![image](https://github.com/brentyi/tyro/assets/13544922/312c1b51-b34f-42f0-b7c8-461585e2790a)

**Comment by tungalbert99** [comment]
Wondering if this is a pydantic specific thing 🤔 since it seems to work in an example https://brentyi.github.io/tyro/examples/02_nesting/04_nesting_in_containers/

**Comment by brentyi** [comment]
Yes sorry for the trouble here, I think this is the same issue as #107!

**Comment by tungalbert99** [comment]
One thing I'm still noticing is that the list of nested models is a little wonky. I'm not able to add a second FlaskConfig in the specification?

**Comment by brentyi** [comment]
Sorry yeah, that seems like expected behavior -- unfortunately we don't currently support appending to dynamically-sized lists of structures like this.

If you have a field like `flasks: list[FlaskConfig] = [FlaskConfig(...), FlaskConfig(...), FlaskConfig(...)]`, `tyro` will currently let you override values in each `FlaskConfig` object, but we don't have the ability to remove elements from the list or append new ones. 

I imagine this is what you're seeing, where you have a length-1 default list and all `tyro` lets you do is override values in this list. A similar behavior also shows up in the `color_tuple_alt: tuple[Color, ...]` field in [this nesting example](https://brentyi.github.io/tyro/examples/02_nesting/04_nesting_in_containers/).

Adding more functionality here is probably doable with a nontrivial amount of thought, in the meantime some workarounds I think are unideal but could work are:
- Create a long default list, and add an extra argument to specify which ones in the list are actually enabled
- Break down the list of structs into a struct of lists (like `id: int` becomes `ids: list[int]`)
- Parse the list as a string, JSON, etc
- Replace `FlaskConfig` with a tuple, like this should work because `source_flasks` gets collapsed to a single argument:
```
FlaskConfig = tuple[str, SourceFlaskSize, int, int | None]

class Config(pydantic.BaseModel):
    source_flasks: list[FlaskConfig]
```

**Comment by tungalbert99** [comment]
I like the tuple idea thank you!
