### ISSUE TITLE
Super weird edge case with `runtime_checkable`

### ISSUE THREAD

**Issue by kvablack** [brentyi/tyro#214]
Hopefully the example is self-explanatory:
```python
import dataclasses
from typing import Protocol, runtime_checkable

import tyro


@runtime_checkable
class DummyProtocol(Protocol):
    pass


@dataclasses.dataclass(frozen=True)
class SubConfigA:
    pass


@dataclasses.dataclass(frozen=True)
class SubConfigB:
    pass


@dataclasses.dataclass
class Config:
    subconfig: DummyProtocol


CONFIGS = {
    "a": Config(subconfig=SubConfigA()),
    "b": Config(subconfig=SubConfigB()),
}

if __name__ == "__main__":
    config = tyro.extras.overridable_config_cli({k: (k, v) for k, v in CONFIGS.items()})
    print(config)

# ❯ python test.py b
# Config(subconfig=SubConfigA())
```

What's so weird is that a bunch of factors all have to be true to trigger the bug:
- The protocol has to be decorated with `@runtime_checkable`
- The subconfigs have to actually implement the protocol (e.g., adding a method to the `DummyProtocol` fixes it)
- The subconfigs have to be frozen

**Comment by brentyi** [comment]
Oof!

The root cause here was bad caching code. I didn't realize that dataclass hashes are invariant to dataclass types + field names:
```python
import dataclasses

@dataclasses.dataclass(frozen=True)
class SubConfigA:
    x: int

@dataclasses.dataclass(frozen=True)
class SubConfigB:
    y: int

# passes
assert hash(SubConfigA(3)) == hash(SubConfigB(3))
```

`functools` doesn't have this problem because it also uses the input type as part of the cache key ([source](https://github.com/python/cpython/blob/2ff3e95ad59a12123cffb2c171044cbeda7d03f5/Lib/functools.py#L493-L496)). I copied this.

**Comment by kvablack** [comment]
wow, thanks for the super quick fix! 😀
