### ISSUE TITLE
Assertion won't be formatted correctly in _arguments

### ISSUE THREAD

**Issue by tovacinni** [brentyi/tyro#28]
Sorry for the issue spamming- but here's a small bug report that this assertion needs to be replaced by an Exception to properly display which fields have issues in the defaults. I would submit a PR but I'll probably get the type of Exception to use wrong :D

https://github.com/brentyi/tyro/blob/e88e690e14ffe87e13419fa2b6427bc77c4ae336/tyro/_arguments.py#L198-L201

**Comment by brentyi** [comment]
Aha thanks! Partially addressed this by fixing the broken f-string, so the assertion error should be useful now.

Need to think about whether this should be converted to an exception. 
I'm leaning slightly toward keeping it as an assert because (1) it doesn't seem like it would ever need to be caught, (2) code that causes this problem would usually be flagged by a type checker*, and (3) none of the existing custom exceptions (unsupported type annotations, instantiation errors, unsupported nested type errors, etc) seem like a good fit.

*I understand this isn't the case if you're dynamically reading defaults from a YAML. But I'm not sure it's tyro's responsibility if you have a field annotated as `bool` which actually contains a string. Egregious example:
```python
import tyro


def main(x: bool = "False") -> None:
    pass


tyro.cli(main)  # Should trigger the same error.
```
