### ISSUE TITLE
Wondering if this works

### ISSUE THREAD

**Issue by jizongFox** [brentyi/tyro#43]
Hello tyro team, 

Thank you for creating this beautiful tool. 

I am creating a dummy demo to see it tyro can work in this way. Idea is very straightforward. 

```python

import typing as t
from dataclasses import dataclass
from pathlib import Path


@dataclass
class DatasetJitterConfig:
    image_folder: Path


@dataclass
class SwapDatasetConfig:
    image_folder: Path


def func1(config: SwapDatasetConfig):
    print(config)


def func2(config: DatasetJitterConfig):
    print(config)


if __name__ == "__main__":
    import tyro

    tyro.cli(t.Union[func1, func2])


```
and when I run this program, it gives me:
```bash
python filename.py func1 --config.image-folder 1 
```

```bash
Traceback (most recent call last):
  File "/home/jizong/workspace/nerfstudio-github/scripts/dataset_jetter.py", line 114, in <module>
    tyro.cli(t.Union[func1, func2])
  File "/opt/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/tyro/_cli.py", line 171, in cli
    output = _cli_impl(
  File "/opt/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/tyro/_cli.py", line 422, in _cli_impl
    out, consumed_keywords = _calling.call_from_args(
  File "/opt/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/tyro/_calling.py", line 155, in call_from_args
    value, consumed_keywords_child = call_from_args(
  File "/opt/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/tyro/_calling.py", line 34, in call_from_args
    f, type_from_typevar, field_list = _fields.field_list_from_callable(
  File "/opt/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/tyro/_fields.py", line 201, in field_list_from_callable
    raise _instantiators.UnsupportedTypeAnnotationError(field_list.message)
tyro._instantiators.UnsupportedTypeAnnotationError: `default_instance` is supported only for select types: dataclasses, lists, NamedTuple, TypedDict, etc.
```
Could you please give me some suggestion on this demo?

Best

**Comment by brentyi** [comment]
Hi!

What version of `tyro` are you using? I just tried running your example as-is with the latest version + Python 3.8 and had no issues.

In general putting functions into the Union is not really well-supported behavior though, since the Union is meant to take types. You can fix this by taking the Union over the config objects and either moving functionality into methods within each config class (example: https://github.com/nerfstudio-project/nerfstudio/blob/main/scripts/exporter.py) or by doing `config = tyro.cli(Union[DatasetJitterConfig, SwapDatasetConfig])` and adding some `isinstance()` logic on the returned config object.

**Comment by jizongFox** [comment]
Hello @brentyi 

I was using tyro 0.4.0 while updating it to 0.4.2 resolved this problem. 

Thank you!

Best
