### ISSUE TITLE
How to overide a non-empty tuple with an empty tuple in the command line?

### ISSUE THREAD

**Issue by ShenhanQian** [brentyi/tyro#56]
For an example shown below, we have a config item `x` as a non-empty tuple.
```python
# main.py
@dataclass()
class BaseConfig:
    x: tuple[str, ...] = ("a", "b", "c")

if __name__ == "__main__":
    config = tyro.cli(BaseConfig)
```
We can overwrite the values in the tuple with the following command:
```shell
python main.py --x d e f
```

But how can we overwrite it with an empty tuple? The command below does not work.
```shell
python main.py --x
```

**Comment by brentyi** [comment]
Hi Shenhan!

Yeah, the way things are set up currently is that we always require at least 1 argument for variable-length fields. There isn't a good reason for this limitation, and we can fix it by doing a find-and-replace of `"+"` for `"*"` in [_instantiators.py](https://github.com/brentyi/tyro/blob/main/tyro/_instantiators.py).

If you're open to making a PR for this (and check that it works) I'd be happy to merge it, otherwise I can do it in the next few days.

As a quick fix, you could also replace `tuple[str, ...]` with `None | tuple[str, ...]` to allow setting the field to `None`.

**Comment by brentyi** [comment]
@ShenhanQian empty sequences are now supported in the latest release!

**Comment by ShenhanQian** [comment]
Thanks so much for your efforts and support! @brentyi
