### ISSUE TITLE
Multiple Base Configurations

### ISSUE THREAD

**Issue by kevin-thankyou-lin** [brentyi/tyro#99]
In the example from [base configurations](https://brentyi.github.io/tyro/examples/03_config_systems/01_base_configs/#base-configurations), it seems like all the objects are instantiated first and then one gets selected / modified by the user.

However, there's the case where:
i) some of the options are such that the default arguments don't always work (e.g., some file paths mightn't exist)
ii) said options aren't what the user wants, so technically we don't care that the default arguments don't work

For example, the following dataclass might be a nested config inside a base config:

```
@dataclass
class MultiCameraConfig:
    camera_cfgs: List[CameraConfig] = field(default_factory=list)
    camera_intrinsics_dir: Optional[pathlib.Path] = None
    camera_extrinsics_path: Optional[pathlib.Path] = None

    def __post_init__(self):
        if self.camera_cfgs is not None:
            assert camera_intrinsics_dir is not None, "..."
            ...
```
 

Then,

```
env_configs: Dict[str, EnvConfig] = {
    "real-env": EnvConfig(
        multi_camera_cfg=MultiCameraConfig(
            camera_cfgs=None,
            camera_intrinsics_dir="random_default_path",
            camera_extrinsics_path="random_default_path",
        )
    ),
    "sim-env": EnvConfig(
        multi_camera_cfg = field(
            default_factory=lambda: MultiCameraConfig(
                # so ran other script and pasting values here
                camera_cfgs=[
                    CameraConfig(
                        ...
                    ),

EnvConfigUnion = tyro.extras.subcommand_type_from_defaults(
    env_configs,
    prefix_names=False,  # Omit prefixes in subcommands themselves.
)

AnnotatedEnvConfigUnion = tyro.conf.OmitSubcommandPrefixes[EnvConfigUnion]  # Omit prefixes of flags in subcommands.

```

where both `EnvConfig` `EnvConfig` are created (and one might trigger an assertion even though that's not the option the user eventually chooses)

Is there a nice way around this?

**Comment by brentyi** [comment]
It's hard to avoid instantiating the provided default objects, since they're needed for things like helptext generation (which currently always happens, even if the helptext isn't being printed), default subcommand matching[^1], and — if the corresponding subcommand is selected — need to be instantiated in their original form before `tyro` can use the CLI flags to override values inside of them.

The easiest suggestion I can think of is to move validation logic like this out of `__post_init__`; you could add a `.validate()` method or something similar?

[^1]: Default subcommand matching means: given a field that's transformed to subcommands `x: Union[A, B, C] = some_object`, does `some_object` correspond to `A`, `B`, or `C`?

**Comment by kevin-thankyou-lin** [comment]
Gotcha - this sounds reasonable. Thanks!
